# permissions for end users to edit mycrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mycrd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-operator
    app.kubernetes.io/part-of: kubebuilder-operator
    app.kubernetes.io/managed-by: kustomize
  name: mycrd-editor-role
rules:
- apiGroups:
  - kubebuilder.operator.test.kubebuilder-operator
  resources:
  - mycrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebuilder.operator.test.kubebuilder-operator
  resources:
  - mycrds/status
  verbs:
  - get
